auth0:
  audience: ${AUTH0_AUDIENCE}
  domain: ${AUTH0_DOMAIN}
  
springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc: 
          batch_size: 10000
        generate_statistics: true
        order_inserts: true
  main:
    allow-bean-definition-overriding: true 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
    
logging:
  level:
    org:  
      hibernate: info 
